# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-03 09:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('main_image', models.CharField(max_length=200, validators=[django.core.validators.URLValidator])),
                ('url', models.CharField(max_length=200, unique=True, validators=[django.core.validators.URLValidator])),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, validators=[django.core.validators.URLValidator])),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, validators=[django.core.validators.URLValidator])),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.Article')),
            ],
        ),
    ]
