# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-03 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_article_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='article',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
